### ISSUE TITLE
Multiple App Configuration pages show updated date as 'Last updated [{LAST_UPDATED_DATE}]'

### ISSUE THREAD

**Issue by brnnnfx** [ibm-cloud-docs/app-configuration#4]
### Which topic are you reporting about?

![Screenshot 2024-12-04 at 8 48 26 AM](https://github.com/user-attachments/assets/03d9ef57-0c90-4349-a8ef-744eb98e1964)

Multiple pages are affected:
- https://cloud.ibm.com/docs/app-configuration?topic=app-configuration-ac-environments
- https://cloud.ibm.com/docs/app-configuration?topic=app-configuration-ac-collections
- https://cloud.ibm.com/docs/app-configuration?topic=app-configuration-ac-feature-flags
- https://cloud.ibm.com/docs/app-configuration?topic=app-configuration-ac-properties
- https://cloud.ibm.com/docs/app-configuration?topic=app-configuration-ac-snapshots
- https://cloud.ibm.com/docs/app-configuration?topic=app-configuration-ac-settings
- https://cloud.ibm.com/docs/app-configuration?topic=app-configuration-ac-integrations
- https://cloud.ibm.com/docs/app-configuration?topic=app-configuration-ac-int-key-management
- https://cloud.ibm.com/docs/app-configuration?topic=app-configuration-ac-sm-integration
- https://cloud.ibm.com/docs/app-configuration?topic=app-configuration-ac-toolchain-integration
- https://cloud.ibm.com/docs/app-configuration?topic=app-configuration-ac-manage-workflow
- https://cloud.ibm.com/docs/app-configuration?topic=app-configuration-ac-offline
- https://cloud.ibm.com/docs/app-configuration?topic=app-configuration-ac-backup-restore-configuration
- https://cloud.ibm.com/docs/app-configuration?topic=app-configuration-ac-monitoring
- https://cloud.ibm.com/docs/app-configuration?topic=app-configuration-ac-ha
- https://cloud.ibm.com/docs/app-configuration?topic=app-configuration-ac-sample-apps
- https://cloud.ibm.com/docs/app-configuration?topic=app-configuration-ac-faqs-operations
- https://cloud.ibm.com/docs/app-configuration?topic=app-configuration-ac-troubleshooting-one
- https://cloud.ibm.com/docs/app-configuration?topic=app-configuration-ac-troubleshooting-two
- https://cloud.ibm.com/docs/app-configuration?topic=app-configuration-ac-troubleshooting-segment
- https://cloud.ibm.com/docs/app-configuration?topic=app-configuration-ac-troubleshooting-toggle
- https://cloud.ibm.com/docs/app-configuration?topic=app-configuration-ac-troubleshooting-def-value
- https://cloud.ibm.com/docs/app-configuration?topic=app-configuration-ac-troubleshooting-del
- https://cloud.ibm.com/docs/app-configuration?topic=app-configuration-ac-troubleshooting-rate-limiting
- https://cloud.ibm.com/docs/app-configuration?topic=app-configuration-ac-ip-address-not-allowed

### What do you think needs to be updated?

The string should show date stamp of the most recent update.

**Comment by KentHall2018** [comment]
thanks for opening this issue. it has been fixed and the last updated dates are now showing up
